import * as React from 'react';
export type IconName =
  | "CryptoIconsSquareProperty1Aave"
  | "CryptoIconsSquareProperty1Algorand"
  | "CryptoIconsSquareProperty1Avalanche"
  | "CryptoIconsSquareProperty1AxieInfinity"
  | "CryptoIconsSquareProperty1BNB"
  | "CryptoIconsSquareProperty1Binance"
  | "CryptoIconsSquareProperty1Bitcoin"
  | "CryptoIconsSquareProperty1Cardano"
  | "CryptoIconsSquareProperty1Chainlink"
  | "CryptoIconsSquareProperty1Cosmos"
  | "CryptoIconsSquareProperty1Cronos"
  | "CryptoIconsSquareProperty1Dai"
  | "CryptoIconsSquareProperty1Dash"
  | "CryptoIconsSquareProperty1Decentraland"
  | "CryptoIconsSquareProperty1Dogecoin"
  | "CryptoIconsSquareProperty1ECash"
  | "CryptoIconsSquareProperty1Elrond"
  | "CryptoIconsSquareProperty1Eos"
  | "CryptoIconsSquareProperty1Ethereum"
  | "CryptoIconsSquareProperty1FTXToken"
  | "CryptoIconsSquareProperty1Flow"
  | "CryptoIconsSquareProperty1Graph"
  | "CryptoIconsSquareProperty1Hedera"
  | "CryptoIconsSquareProperty1Kava"
  | "CryptoIconsSquareProperty1Litecoin"
  | "CryptoIconsSquareProperty1Maker"
  | "CryptoIconsSquareProperty1Monero"
  | "CryptoIconsSquareProperty1NearProtocol"
  | "CryptoIconsSquareProperty1Neo"
  | "CryptoIconsSquareProperty1Nexo"
  | "CryptoIconsSquareProperty1PancakeSwap"
  | "CryptoIconsSquareProperty1Polkadot"
  | "CryptoIconsSquareProperty1Polygon"
  | "CryptoIconsSquareProperty1Quant"
  | "CryptoIconsSquareProperty1ShibaInu"
  | "CryptoIconsSquareProperty1Solana"
  | "CryptoIconsSquareProperty1Stellar"
  | "CryptoIconsSquareProperty1Tether"
  | "CryptoIconsSquareProperty1Tezos"
  | "CryptoIconsSquareProperty1ThetaNetwork"
  | "CryptoIconsSquareProperty1Tron"
  | "CryptoIconsSquareProperty1TrueUSD"
  | "CryptoIconsSquareProperty1USDCoin"
  | "CryptoIconsSquareProperty1Uniswap"
  | "CryptoIconsSquareProperty1Vechain"
  | "CryptoIconsSquareProperty1XRP"
  | "CryptoIconsSquareProperty1Zcash";
export interface CryptoIconSquareProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const CryptoIconSquare: React.FC<CryptoIconSquareProps>;
export default CryptoIconSquare;
