import * as React from 'react';
export type IconName =
  | "CryptoIconsRoundProperty1Aave"
  | "CryptoIconsRoundProperty1Algorand"
  | "CryptoIconsRoundProperty1Avalanche"
  | "CryptoIconsRoundProperty1BNB"
  | "CryptoIconsRoundProperty1Bitcoin"
  | "CryptoIconsRoundProperty1Cardano"
  | "CryptoIconsRoundProperty1Chainlink"
  | "CryptoIconsRoundProperty1Cosmos"
  | "CryptoIconsRoundProperty1Cronos"
  | "CryptoIconsRoundProperty1Dai"
  | "CryptoIconsRoundProperty1Dash"
  | "CryptoIconsRoundProperty1Dogecoin"
  | "CryptoIconsRoundProperty1ECash"
  | "CryptoIconsRoundProperty1Elrond"
  | "CryptoIconsRoundProperty1Eos"
  | "CryptoIconsRoundProperty1Ethereum"
  | "CryptoIconsRoundProperty1FTXToken"
  | "CryptoIconsRoundProperty1Flow"
  | "CryptoIconsRoundProperty1Graph"
  | "CryptoIconsRoundProperty1Hedera"
  | "CryptoIconsRoundProperty1Kava"
  | "CryptoIconsRoundProperty1Litecoin"
  | "CryptoIconsRoundProperty1Maker"
  | "CryptoIconsRoundProperty1Monero"
  | "CryptoIconsRoundProperty1NearProtocol"
  | "CryptoIconsRoundProperty1Neo"
  | "CryptoIconsRoundProperty1Nexo"
  | "CryptoIconsRoundProperty1PancakeSwap"
  | "CryptoIconsRoundProperty1Polkadot"
  | "CryptoIconsRoundProperty1Polygon"
  | "CryptoIconsRoundProperty1Quant"
  | "CryptoIconsRoundProperty1ShibaInu"
  | "CryptoIconsRoundProperty1Solana"
  | "CryptoIconsRoundProperty1Stellar"
  | "CryptoIconsRoundProperty1Tether"
  | "CryptoIconsRoundProperty1Tezos"
  | "CryptoIconsRoundProperty1ThetaNetwork"
  | "CryptoIconsRoundProperty1Tron"
  | "CryptoIconsRoundProperty1TrueUSD"
  | "CryptoIconsRoundProperty1USDCoin"
  | "CryptoIconsRoundProperty1Uniswap"
  | "CryptoIconsRoundProperty1Vechain"
  | "CryptoIconsRoundProperty1XRP"
  | "CryptoIconsRoundProperty1Zcash";
export interface CryptoIconRoundProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const CryptoIconRound: React.FC<CryptoIconRoundProps>;
export default CryptoIconRound;
